import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Devesh B</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center py-4">
          <h1 className="text-4xl text-white font-extrabold">Devesh B</h1>
      </main>

      
    </div>
  )
}

export default Home
